name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.15.9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format Check
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

      - name: Generate Prisma Client
        run: pnpm --filter @bahrawy/db generate

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: Validate Docker Compose
        run: pnpm compose:validate
